server:
  port: 8081
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/well_log_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true      
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 2

# JWT 令牌
jwt:
  secret: YXNkZmFzZGZjenh2Y3p4dnF3ZXJxZXdycXdlcmRzYWZhc2RmYXNkZg==
  access-expiration: 3600 # 1h
  refresh-expiration: 604800 # 7d

# 文件上传目录（按顺序尝试，第一个可用的就用）
app:
  upload:
    dirs:
      - E:\Others\upload
      - D:\project-upload
      - C:\project-upload
      # Linux: - /www/wwwroot/xy/upload
